language: php

pipeline:

  s3:
    settings:
      provider: s3
      region: ${S3_REGION}
      access_key_id: ${S3_ACCESS_KEY_ID}
      secret_access_key: ${S3_SECRET_ACCESS_KEY}
      bucket: pcit-deployer-s3
      acl: public_read
      local_dir: src
      upload_dir: nightly
      # endpoint: https://storage.khs1994.com
      endpoint: ${S3_ENTRYPOINT}
      minio: true

  s3_2:
    settings:
      provider: s3
      region: ${S3_REGION}
      access_key_id: ${S3_ACCESS_KEY_ID}
      secret_access_key: ${S3_SECRET_ACCESS_KEY}
      bucket: ${S3_BUCKET}
      acl: public_read
      local_dir: src
      # upload_dir: pcit-nightly
      # endpoint: https://storage.khs1994.com
      endpoint: ${S3_ENTRYPOINT}
      minio: true
